/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import classes.gerarpdf;
import classes.preprocessamento;
import classes.sentimentos;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import static com.itextpdf.text.pdf.PdfObject.NULL;
import com.itextpdf.text.pdf.PdfWriter;
import com.kennycason.kumo.CollisionMode;
import com.kennycason.kumo.WordCloud;
import com.kennycason.kumo.WordFrequency;
import com.kennycason.kumo.bg.RectangleBackground;
import com.kennycason.kumo.font.scale.LinearFontScalar;
import com.kennycason.kumo.nlp.FrequencyAnalyzer;
import com.kennycason.kumo.palette.ColorPalette;
import com.restfb.Connection;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.FacebookClient.AccessToken;
import com.restfb.Parameter;
import com.restfb.types.Group;
import com.restfb.types.Post;
import com.restfb.types.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import static jdk.nashorn.tools.ShellFunctions.input;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author lipe_
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setIcon();
    }
    
    int cont =0,alegria=0,desgosto=0, medo=0, raiva=0, surpresa=0,tristeza=0, palavrao=0, clicado=0, fraudes=0;
    int grafalegria=0,grafdesgosto=0, grafmedo=0, grafraiva=0, grafsurpresa=0,graftristeza=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        quantidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(59, 89, 152));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(59, 89, 152));
        jPanel2.setForeground(new java.awt.Color(59, 89, 152));

        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(216, 223, 234));
        jLabel3.setText("                        ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(216, 223, 234));
        jLabel4.setText("                         ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(216, 223, 234));
        jLabel5.setText("    ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(216, 223, 234));
        jLabel6.setText("                         ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(216, 223, 234));
        jLabel7.setText("    ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Análise Gráfica");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exportar Postagens Analisadas");
        jButton2.setBorder(null);
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel3))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        quantidade.setEditable(true);
        quantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "50", "100", "200", "500", "1000", "10000", "Todas" }));
        quantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quantidade.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 132, 180));
        jLabel1.setText("URL");

        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/busca.jpg"))); // NOI18N
        iniciar.setBorderPainted(false);
        iniciar.setContentAreaFilled(false);
        iniciar.setPreferredSize(new java.awt.Dimension(26, 26));
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarMouseExited(evt);
            }
        });
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 132, 180));
        jLabel2.setText("Limite de postagens");

        entrada.setForeground(new java.awt.Color(204, 204, 204));
        entrada.setText("Insira sua URL de uma página ou grupo do facebook aqui");
        entrada.setMinimumSize(new java.awt.Dimension(6, 25));
        entrada.setPreferredSize(new java.awt.Dimension(161, 25));
        entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
        
        
        ///////////////ZERANDO VARIÁVEIS DE SENTIMENTOS//////////////////////////
        cont=0;
        alegria=0;
        String pdfalegria = "";
        desgosto=0;
        String pdfdesgosto = "";
        medo=0;
        String pdfmedo = "";
        raiva=0;
        String pdfraiva = "";
        surpresa=0;
        String pdfsurpresa = "";
        tristeza=0;
        String pdftristeza = "";
        palavrao=0;
        String pdfpalavrao = "";
        fraudes=0;
         String pdffraudes = "";
         
         String juntainfo ="";
         
         
        grafalegria=0;
        grafdesgosto=0;
        grafmedo=0;
        grafraiva=0;
        grafsurpresa=0;
        graftristeza=0;
        
        ////////////////////CRIA METODO PARA CLASSE GERARPDF///////////
        gerarpdf criapdf = new gerarpdf();
        
        
        ////////////////////CHAMA METODO QUE CRIA PDF///////////
        criapdf.cria();
        
        
        
        /////////////////CRIA ARQUIVO PARA A NUVEM DE PALAVRAS///////////////////
        FileWriter arq = null;
        try {
            arq = new FileWriter("arquivo.txt");
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintWriter gravaarquivo = new PrintWriter(arq);
        
        

int ini,fim;
String url = entrada.getText();
if (url.contains("groups")){
    cont =1;
}else{
    cont =0;
}
try{
    if(cont==1){
        //se for grupo é daqui
        ini = url.indexOf("groups/");
        fim = url.lastIndexOf("/");
        System.out.println(url.substring(ini+7, fim));
        url = url.substring(ini+7, fim);
    }else{
        //se for pagina é daqui para baixo
        ini = url.indexOf(".com/");
        fim = url.lastIndexOf("/");
        System.out.println(url.substring(ini+5, fim));
        url = url.substring(ini+5, fim);
    }
}catch (StringIndexOutOfBoundsException e) {
    JOptionPane.showMessageDialog(null, "O endereço digitado é inválido!");
}
/////////////////////////////////////////////////////////////////////////////
/////////////CRIA CONEXÃO DE DADOS COM O FACEBOOK
String accessToken = "EAACEdEose0cBAKpiaYaWY3HIGcdQQtEKnu3axpcHGEIRvIBUIZCuaYzKQHsCEPFDHAiQkEiqZBoxUyHOXtWpUNRb7QTV0ZA83xvZAsOoNBDHZAZAU546VJaZAnMCIlZALT0OaeTqaIFTZCPs6gOZAanB71NgzjKfXZAnSrWxFd9zCPlMbca7JwP3er1LrYMI9BobJfCIRlC4ZBw4hgZDZD";
FacebookClient fbClient = new DefaultFacebookClient(accessToken) ;
System.out.println(accessToken);
Connection<Post> postFeed = fbClient.fetchConnection( url + "/feed", Post.class, Parameter.with("fields", "from,message"));
////////////////SELECIONA O NÚMERO DE POSTAGENS
int contagem = 0;
String valor = quantidade.getSelectedItem().toString();
if("Todas".equals(valor))
{
    contagem = 999999999;
}else
{
    contagem =  Integer.parseInt((String)quantidade.getSelectedItem());
}
for(List<Post> postPage : postFeed){
    
    for(Post aPost : postPage){
        
        String passa = (" "+aPost.getMessage()+" ");//+" : fb.com/"+aPost.getId());aPost.getFrom().getName()+
        String usuariopdf = (aPost.getFrom().getName());//+ "Postagem: "+aPost.getMessage()+"Link:"+": fb.com/"+aPost.getId());
        String postagempdf = (aPost.getMessage());//+"Link:"+": fb.com/"+aPost.getId());
        String linkpdf = (aPost.getId());
        
        
//posta no textarea a postagem
//postagens.append(passa+"\n");


//////////chama a classe para preprocessamento      
preprocessamento postado = new preprocessamento();//cria objeto para chamar a classe

String especiais = postado.especiais(passa);//joga a string da postagem no metodo de remover caracteres especiais

String stopwords = postado.stopwords(especiais);//joga a srting sem caracteres no metodo de remover stopwords

gravaarquivo.println(stopwords);
/////////chama a classe de contagem de sentimentos
sentimentos feel = new sentimentos();//cria objeto para chamar a classe

             
//////////retorna contagem de palavras relacionadas a desgosto
int retornodesgosto = feel.desgosto(stopwords);
desgosto = desgosto + retornodesgosto;
if(retornodesgosto>0){
    grafdesgosto++;
    pdfdesgosto = "DESGOSTO, ";
}else  pdfdesgosto = "";

//////////retorna contagem de palavras relacionadas a medo
int retornomedo = feel.medo(stopwords);
medo = medo + retornomedo;
if(retornomedo>0){
    grafmedo++;
    pdfmedo = "MEDO, ";
}else  pdfmedo = "";

//////////retorna contagem de palavras relacionadas a raiva
int retornoraiva = feel.raiva(stopwords);
raiva = raiva + retornoraiva;
if(retornoraiva>0){
    grafraiva++;
    pdfraiva = "RAIVA, ";
}else  pdfraiva = "";

//////////retorna contagem de palavras relacionadas a surpresa
int retornosurpresa = feel.surpresa(stopwords);
surpresa = surpresa + retornosurpresa;
if(retornosurpresa>0){
    grafsurpresa++;
    pdfsurpresa = "SURPRESA, ";
}else  pdfsurpresa = "";

//////////retorna contagem de palavras relacionadas a tristeza
int retornotristeza = feel.tristeza(stopwords);
tristeza = tristeza + retornotristeza;
if(retornotristeza>0){
    graftristeza++;
    pdftristeza = "TRISTEZA, ";
}else  pdftristeza = "";

//////////retorna contagem de palavras relacionadas a alegria
int retornoalegria = feel.alegria(stopwords);
alegria = alegria + retornoalegria;
if(retornoalegria>0 && retornotristeza == 0 && retornoraiva==0 && retornomedo==0 && retornodesgosto==0){
    grafalegria++;
    pdfalegria = "ALEGRIA, ";
}else  pdfalegria = "";

//////////retorna contagem de palavroes encontrada
int retornopalavrao = feel.palavrao(stopwords);
palavrao = palavrao + retornopalavrao;

if(retornopalavrao>0){
    pdfpalavrao = "LINGUAGEM INAPROPRIADA, ";
}else  pdfpalavrao = "";

if(palavrao>0)
{
     
    jLabel4.setText("As postagens analisadas podem conter linguagem inapropriada!");
    ImageIcon alerta = new ImageIcon("alerta.png");
            jLabel5.setIcon(alerta);
}else{ 
    jLabel4.setText("As postagens analisadas estão livres de linguagem inapropriada!");
    ImageIcon ok = new ImageIcon("o.png");
            jLabel5.setIcon(ok);
}

//////////retorna contagem de palavras de seguranca encontrada
int retornofraudes = feel.fraudes(stopwords);
fraudes = fraudes + retornofraudes;

if(retornofraudes>0){
    pdffraudes = "PALAVRAS RELACIONADAS A FRAUDES, ";
}else  pdffraudes = "";

if(fraudes>0)
{
    
    jLabel6.setText("Foram encontradas palavras relacionadas a fraudes por phishing!");
    ImageIcon alerta = new ImageIcon("perigo.png");
            jLabel7.setIcon(alerta);
}else{ 
    jLabel6.setText("Não foram encontradas palavras relacionadas a fraudes por phishing!");
    ImageIcon ok = new ImageIcon("o.png");
            jLabel7.setIcon(ok);
}

juntainfo = pdfalegria + pdfdesgosto + pdfmedo + pdfraiva + pdfsurpresa + pdftristeza + pdfpalavrao + pdffraudes;

if(juntainfo.length()<2)
{
    juntainfo="POSTAGEM NEUTRA!";
}
    

////////JOGA INFORMAÇÕES PARA DENTRO DO PDF///////////////
criapdf.grava(usuariopdf, postagempdf, linkpdf, juntainfo );


//////contador do número de postagens
contagem--;
//System.out.println(contagem);

if(contagem==0)
{
            try {
                arq.close();
                worldcloud();
                //habilita o botão do gráfico e da exportação de postagens
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);
                criapdf.fecha();//fecha o documento PDF
                return; } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
      try {
                arq.close();
                worldcloud();
                ImageIcon nuvem = new ImageIcon("wordcloud.jpg");
                jLabel9.setIcon(nuvem);
                //habilita o botão do gráfico e da exportação de postagens
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);
                criapdf.fecha();//fecha o documento PDF
                return; } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
      
      
 
    }//GEN-LAST:event_iniciarActionPerformed

    private void entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMouseClicked
        // TODO add your handling code here:
        
        if(clicado==0){
        entrada.setText("");
        entrada.setForeground(Color.BLACK);
        clicado++;
        }
    }//GEN-LAST:event_entradaMouseClicked

    private void iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseEntered
        // TODO add your handling code here:
        ImageIcon buscafoco = new ImageIcon("buscafocada.jpg");
            iniciar.setIcon(buscafoco);
            iniciar.repaint();
    }//GEN-LAST:event_iniciarMouseEntered

    private void iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseExited
        // TODO add your handling code here:
        ImageIcon buscafoco = new ImageIcon("busca.jpg");
            iniciar.setIcon(buscafoco);
            iniciar.repaint();
    }//GEN-LAST:event_iniciarMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        ////GERAR PDF COM AS POSTAGENS
         gerarpdf criapdf = new gerarpdf();
         criapdf.abre();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        grafico();
    }//GEN-LAST:event_jButton1ActionPerformed

    //////////////////////FUNÇÃO PARA GERAR WORDCLOUD///////////////////////////////
   public void worldcloud() throws IOException{       
            
            
            final FrequencyAnalyzer frequencyAnalyzer = new FrequencyAnalyzer();
            final List<WordFrequency> wordFrequencies = frequencyAnalyzer.load("arquivo.txt");
            final Dimension dimension = new Dimension(400, 200);
            final WordCloud wordCloud = new WordCloud(dimension, CollisionMode.RECTANGLE);
            wordCloud.setPadding(1);
            wordCloud.setBackground(new RectangleBackground(dimension));
            wordCloud.setColorPalette(new ColorPalette(new Color(0xFF8C00), new Color(0x32CD32), new Color(0xC71585), new Color(0x40C5F1), new Color(0x40D3F1), new Color(0xFFFFFF)));
            wordCloud.setFontScalar(new LinearFontScalar(10, 40));
            wordCloud.build(wordFrequencies);
            wordCloud.writeToFile("wordcloud.jpg");
            
            BufferedImage  image = ImageIO.read(new File("wordcloud.jpg"));           
            ImageIcon dede = new ImageIcon(image);
            jLabel9.setIcon(dede);
            jLabel3.setText("Palavras mais frequentes");
            
   }
   
   /////////////////////////FUNÇÃO PARA GERAR O GRÁFICO DE PIZZA DE SENTIMENTOS/////////////
   public void grafico(){
       
       
       double total = (grafalegria + grafdesgosto + grafmedo + grafraiva + grafsurpresa + graftristeza);
       
      DefaultPieDataset grafico = new  DefaultPieDataset();
      grafico.setValue("ALEGRIA", (grafalegria/total)*100);
      grafico.setValue("DESGOSTO", (grafdesgosto/total)*100);
      grafico.setValue("MEDO", (grafmedo/total)*100);
      grafico.setValue("RAIVA", (grafraiva/total)*100);
      grafico.setValue("SURPRESA", (grafsurpresa/total)*100);
      grafico.setValue("TRISTEZA", (graftristeza/total)*100);
      JFreeChart chart = ChartFactory.createPieChart("Relação entre postagem e sentimentos",grafico,true,true,true);
      PiePlot plotar =(PiePlot)chart.getPlot();
      ChartFrame frame = new ChartFrame("Relação entre postagem e sentimentos", chart);
      frame.setVisible(true);
      frame.setSize(600,400);
   }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entrada;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> quantidade;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        ///////////ALTERANDO O ICONE DA APLICAÇÃO//////////////////////////////
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
